In [105]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [106]:
M = np.array([
    [1, -1, 1/4],
    [-1, 5/4, 0],
    [1/4, -1, 1]
])

In [107]:
np.linalg.solve(M, np.array([1, 0, 0]))

array([2.96296296, 2.37037037, 1.62962963])

In [108]:
my_s = pd.Series([1, 2, 3])
my_s.shift(1)

0    NaN
1    1.0
2    2.0
dtype: float64

In [109]:
s = [1.62434536,  1.98719617,  1.61176108,  0.23404356,  0.20835024, -2.1179662,
 -1.7772783, -2.24935382, -2.1424689,  -2.23773417, -0.74708664, -1.82332947,
 -2.7616089,  -3.63569774, -2.91591724, -3.4385123,  -3.80786085, -4.76978791,
 -5.15241597, -4.60838607, -5.17649067, -4.18829428, -2.48672609, -0.79575907,
  1.21914613,  1.77619176,  1.93876306,  1.02948874,
  0.13848555,  0.09305955,
 -0.63139623, -1.4665456,  -2.62955207, -4.11389978, -5.57057245, -6.29268466,
 -7.62043943, -7.93096921, -6.15266733, -4.02640327]
s = pd.Series(s, name="Y")
s_dt = s - s.mean()

In [110]:
s = s
s

0     1.624345
1     1.987196
2     1.611761
3     0.234044
4     0.208350
5    -2.117966
6    -1.777278
7    -2.249354
8    -2.142469
9    -2.237734
10   -0.747087
11   -1.823329
12   -2.761609
13   -3.635698
14   -2.915917
15   -3.438512
16   -3.807861
17   -4.769788
18   -5.152416
19   -4.608386
20   -5.176491
21   -4.188294
22   -2.486726
23   -0.795759
24    1.219146
25    1.776192
26    1.938763
27    1.029489
28    0.138486
29    0.093060
30   -0.631396
31   -1.466546
32   -2.629552
33   -4.113900
34   -5.570572
35   -6.292685
36   -7.620439
37   -7.930969
38   -6.152667
39   -4.026403
Name: Y, dtype: float64

In [111]:
s_dt = pd.Series(s - s.mean(), name="Y")
s_dt.head()

0    3.909520
1    4.272371
2    3.896935
3    2.519218
4    2.493525
Name: Y, dtype: float64

In [112]:
s_dt.shift(1, fill_value=0)

0     0.000000
1     3.909520
2     4.272371
3     3.896935
4     2.519218
5     2.493525
6     0.167208
7     0.507896
8     0.035821
9     0.142705
10    0.047440
11    1.538088
12    0.461845
13   -0.476435
14   -1.350523
15   -0.630743
16   -1.153338
17   -1.522687
18   -2.484614
19   -2.867242
20   -2.323212
21   -2.891316
22   -1.903120
23   -0.201552
24    1.489415
25    3.504320
26    4.061366
27    4.223937
28    3.314663
29    2.423660
30    2.378234
31    1.653778
32    0.818629
33   -0.344378
34   -1.828725
35   -3.285398
36   -4.007510
37   -5.335265
38   -5.645795
39   -3.867493
Name: Y, dtype: float64

In [113]:
df = pd.DataFrame([s_dt.shift(i) for i in range(10)]).T.dropna(axis=0)
df.columns = [f"Y_{i}" for i in range(10)]
df

Y_0       Y_1       Y_2       Y_3       Y_4       Y_5       Y_6  \
9   0.047440  0.142705  0.035821  0.507896  0.167208  2.493525  2.519218   
10  1.538088  0.047440  0.142705  0.035821  0.507896  0.167208  2.493525   
11  0.461845  1.538088  0.047440  0.142705  0.035821  0.507896  0.167208   
12 -0.476435  0.461845  1.538088  0.047440  0.142705  0.035821  0.507896   
13 -1.350523 -0.476435  0.461845  1.538088  0.047440  0.142705  0.035821   
14 -0.630743 -1.350523 -0.476435  0.461845  1.538088  0.047440  0.142705   
15 -1.153338 -0.630743 -1.350523 -0.476435  0.461845  1.538088  0.047440   
16 -1.522687 -1.153338 -0.630743 -1.350523 -0.476435  0.461845  1.538088   
17 -2.484614 -1.522687 -1.153338 -0.630743 -1.350523 -0.476435  0.461845   
18 -2.867242 -2.484614 -1.522687 -1.153338 -0.630743 -1.350523 -0.476435   
19 -2.323212 -2.867242 -2.484614 -1.522687 -1.153338 -0.630743 -1.350523   
20 -2.891316 -2.323212 -2.867242 -2.484614 -1.522687 -1.153338 -0.630743   
21 -1.903120 -2.891316 -2.323212 -2.867242 -2.484614 -1.522687 -1.153338   
22 -0.201552 -1.903120 -2.891316 -2.323212 -2.867242 -2.484614 -1.522687   
23  1.489415 -0.201552 -1.903120 -2.891316 -2.323212 -2.867242 -2.484614   
24  3.504320  1.489415 -0.201552 -1.903120 -2.891316 -2.323212 -2.867242   
25  4.061366  3.504320  1.489415 -0.201552 -1.903120 -2.891316 -2.323212   
26  4.223937  4.061366  3.504320  1.489415 -0.201552 -1.903120 -2.891316   
27  3.314663  4.223937  4.061366  3.504320  1.489415 -0.201552 -1.903120   
28  2.423660  3.314663  4.223937  4.061366  3.504320  1.489415 -0.201552   
29  2.378234  2.423660  3.314663  4.223937  4.061366  3.504320  1.489415   
30  1.653778  2.378234  2.423660  3.314663  4.223937  4.061366  3.504320   
31  0.818629  1.653778  2.378234  2.423660  3.314663  4.223937  4.061366   
32 -0.344378  0.818629  1.653778  2.378234  2.423660  3.314663  4.223937   
33 -1.828725 -0.344378  0.818629  1.653778  2.378234  2.423660  3.314663   
34 -3.285398 -1.828725 -0.344378  0.818629  1.653778  2.378234  2.423660   
35 -4.007510 -3.285398 -1.828725 -0.344378  0.818629  1.653778  2.378234   
36 -5.335265 -4.007510 -3.285398 -1.828725 -0.344378  0.818629  1.653778   
37 -5.645795 -5.335265 -4.007510 -3.285398 -1.828725 -0.344378  0.818629   
38 -3.867493 -5.645795 -5.335265 -4.007510 -3.285398 -1.828725 -0.344378   
39 -1.741229 -3.867493 -5.645795 -5.335265 -4.007510 -3.285398 -1.828725   

         Y_7       Y_8       Y_9  
9   3.896935  4.272371  3.909520  
10  2.519218  3.896935  4.272371  
11  2.493525  2.519218  3.896935  
12  0.167208  2.493525  2.519218  
13  0.507896  0.167208  2.493525  
14  0.035821  0.507896  0.167208  
15  0.142705  0.035821  0.507896  
16  0.047440  0.142705  0.035821  
17  1.538088  0.047440  0.142705  
18  0.461845  1.538088  0.047440  
19 -0.476435  0.461845  1.538088  
20 -1.350523 -0.476435  0.461845  
21 -0.630743 -1.350523 -0.476435  
22 -1.153338 -0.630743 -1.350523  
23 -1.522687 -1.153338 -0.630743  
24 -2.484614 -1.522687 -1.153338  
25 -2.867242 -2.484614 -1.522687  
26 -2.323212 -2.867242 -2.484614  
27 -2.891316 -2.323212 -2.867242  
28 -1.903120 -2.891316 -2.323212  
29 -0.201552 -1.903120 -2.891316  
30  1.489415 -0.201552 -1.903120  
31  3.504320  1.489415 -0.201552  
32  4.061366  3.504320  1.489415  
33  4.223937  4.061366  3.504320  
34  3.314663  4.223937  4.061366  
35  2.423660  3.314663  4.223937  
36  2.378234  2.423660  3.314663  
37  1.653778  2.378234  2.423660  
38  0.818629  1.653778  2.378234  
39 -0.344378  0.818629  1.653778

In [114]:
cov_df = np.round(df.cov() / df.cov().iloc[0, 0], 2)
cov_df

Y_0   Y_1   Y_2   Y_3   Y_4   Y_5   Y_6   Y_7   Y_8   Y_9
Y_0  1.00  0.91  0.72  0.47  0.21 -0.03 -0.22 -0.38 -0.47 -0.53
Y_1  0.91  1.00  0.89  0.69  0.44  0.20 -0.04 -0.23 -0.37 -0.46
Y_2  0.72  0.89  0.94  0.81  0.61  0.38  0.15 -0.07 -0.23 -0.36
Y_3  0.47  0.69  0.81  0.81  0.68  0.51  0.30  0.10 -0.08 -0.22
Y_4  0.21  0.44  0.61  0.68  0.68  0.58  0.43  0.25  0.08 -0.07
Y_5 -0.03  0.20  0.38  0.51  0.58  0.63  0.54  0.42  0.27  0.12
Y_6 -0.22 -0.04  0.15  0.30  0.43  0.54  0.60  0.54  0.44  0.30
Y_7 -0.38 -0.23 -0.07  0.10  0.25  0.42  0.54  0.63  0.58  0.49
Y_8 -0.47 -0.37 -0.23 -0.08  0.08  0.27  0.44  0.58  0.68  0.64
Y_9 -0.53 -0.46 -0.36 -0.22 -0.07  0.12  0.30  0.49  0.64  0.73

In [115]:
R = np.array([np.dot(df.iloc[:, 0], df.iloc[:, i]) for i in range(10)]) / 10
np.round(R/R[0], 2)

array([ 1.  ,  0.91,  0.71,  0.46,  0.21, -0.04, -0.24, -0.4 , -0.51,
       -0.57])

In [116]:
m = 3
L = 9

M = np.zeros((m, L-m+1))

for col in range(L-m+1):
    M[:, col] = cov_df.iloc[col+1:col+m+1, 0]
    print("M =")
    print(M)

M

M =
[[0.91 0.   0.   0.   0.   0.   0.  ]
 [0.72 0.   0.   0.   0.   0.   0.  ]
 [0.47 0.   0.   0.   0.   0.   0.  ]]
M =
[[0.91 0.72 0.   0.   0.   0.   0.  ]
 [0.72 0.47 0.   0.   0.   0.   0.  ]
 [0.47 0.21 0.   0.   0.   0.   0.  ]]
M =
[[ 0.91  0.72  0.47  0.    0.    0.    0.  ]
 [ 0.72  0.47  0.21  0.    0.    0.    0.  ]
 [ 0.47  0.21 -0.03  0.    0.    0.    0.  ]]
M =
[[ 0.91  0.72  0.47  0.21  0.    0.    0.  ]
 [ 0.72  0.47  0.21 -0.03  0.    0.    0.  ]
 [ 0.47  0.21 -0.03 -0.22  0.    0.    0.  ]]
M =
[[ 0.91  0.72  0.47  0.21 -0.03  0.    0.  ]
 [ 0.72  0.47  0.21 -0.03 -0.22  0.    0.  ]
 [ 0.47  0.21 -0.03 -0.22 -0.38  0.    0.  ]]
M =
[[ 0.91  0.72  0.47  0.21 -0.03 -0.22  0.  ]
 [ 0.72  0.47  0.21 -0.03 -0.22 -0.38  0.  ]
 [ 0.47  0.21 -0.03 -0.22 -0.38 -0.47  0.  ]]
M =
[[ 0.91  0.72  0.47  0.21 -0.03 -0.22 -0.38]
 [ 0.72  0.47  0.21 -0.03 -0.22 -0.38 -0.47]
 [ 0.47  0.21 -0.03 -0.22 -0.38 -0.47 -0.53]]


array([[ 0.91,  0.72,  0.47,  0.21, -0.03, -0.22, -0.38],
       [ 0.72,  0.47,  0.21, -0.03, -0.22, -0.38, -0.47],
       [ 0.47,  0.21, -0.03, -0.22, -0.38, -0.47, -0.53]])

In [117]:
M[1, :].sum()

0.29999999999999993

__________

In [118]:
S = np.arange(1, 10)
S

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
m = 4

A = np.zeros((m, len(S)-m+1))

for i in range(len(S)-m+1):
    A[:, i] = S[i:i+m]

A

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6., 7.],
       [3., 4., 5., 6., 7., 8.],
       [4., 5., 6., 7., 8., 9.]])

In [120]:
A.T

array([[1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.],
       [4., 5., 6., 7.],
       [5., 6., 7., 8.],
       [6., 7., 8., 9.]])

In [121]:
np.linalg.matrix_rank(A)

2