In [278]:
import numpy as np
import pandas as pd

In [279]:
y_1= np.array([0, 0, 0, 0, 0,  2.7,  7.74,  6.24,   8.32,  8.75, 11.46, 8.94,  11.68, 12.62, 15.13, 13.9,  15.83, 16.12, 18.04, 19.58, 18.9,  22.14, 22.9,  23.5, 24.9,  24.32, 25.88, 26.06, 27.73, 29.53, 29.31, 30.6,  31.31, 32.15, 33.33, 34.99])

y_2=np.array([-1.12,  1.23,  3.66,  3.74,  3.81,  4.11,  5.25,  8.69,  8.05,  8.36, 10.19, 13.1,  12.12, 13.62, 14.3,  14.65, 14.86, 16.65, 17.79, 19.59, 20.84, 21.93, 22.29, 23.89,  23.25, 26.25, 26.51, 26.7,  28.49, 28.92, 31.13, 32.52, 34.19, 31.6,  32.56, 34.5]) 

y_3=np.array([0.16,  1.88,  2.32,  0.98,  3.69,  5.83,  6.23,  7.76,  7.78,  8.8,  10.19, 11.41,  12.2,  13.12, 13.33, 15.38, 16.12, 18.13, 19.2,  19.19, 19.62, 20.36, 22.42, 23.08,  23.66, 25.04, 25.38, 27.7,  27.55, 30.22, 30.4,  31.59, 30.91, 33.17, 34.74, 34.05]) 

y_4=np.array([-0.27,  1.03,  0.63,  3.32,  4.85,  4.14,  6.35,  5.69,  7.96,  7.38, 11.12, 11.41,  11.98, 12.22, 15.27, 16.97, 14.14, 18.24, 19.63, 19.34, 18.8,  21.86, 21.82, 22.4,  22.77, 25.55, 26.79, 26.38, 28.52, 27.86, 30.8,  31.05, 31.81, 32.9,  34.87, 35.75])

y_5=np.array([0.53,  1.14,  2.08,  3.62,  4.23,  5.68,  5.69,  4.57,  9.04, 11.19, 10.44, 10.9,  11.86, 12.88, 14.02, 13.88, 15.48, 16.0, 18.25, 18.7,  20.5,  20.83, 22.99, 23.21,  26.19, 23.1,  25.35, 27.9,  30.53, 28.75, 30.04, 30.77, 33.33, 32.71, 34.68, 34.68])

In [280]:
N = 5
T = 36
L = np.sqrt(N*T)
L

13.416407864998739

In [281]:
Y = np.vstack([y_1, y_2, y_3, y_4, y_5])
Y

array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  2.7 ,  7.74,  6.24,  8.32,
         8.75, 11.46,  8.94, 11.68, 12.62, 15.13, 13.9 , 15.83, 16.12,
        18.04, 19.58, 18.9 , 22.14, 22.9 , 23.5 , 24.9 , 24.32, 25.88,
        26.06, 27.73, 29.53, 29.31, 30.6 , 31.31, 32.15, 33.33, 34.99],
       [-1.12,  1.23,  3.66,  3.74,  3.81,  4.11,  5.25,  8.69,  8.05,
         8.36, 10.19, 13.1 , 12.12, 13.62, 14.3 , 14.65, 14.86, 16.65,
        17.79, 19.59, 20.84, 21.93, 22.29, 23.89, 23.25, 26.25, 26.51,
        26.7 , 28.49, 28.92, 31.13, 32.52, 34.19, 31.6 , 32.56, 34.5 ],
       [ 0.16,  1.88,  2.32,  0.98,  3.69,  5.83,  6.23,  7.76,  7.78,
         8.8 , 10.19, 11.41, 12.2 , 13.12, 13.33, 15.38, 16.12, 18.13,
        19.2 , 19.19, 19.62, 20.36, 22.42, 23.08, 23.66, 25.04, 25.38,
        27.7 , 27.55, 30.22, 30.4 , 31.59, 30.91, 33.17, 34.74, 34.05],
       [-0.27,  1.03,  0.63,  3.32,  4.85,  4.14,  6.35,  5.69,  7.96,
         7.38, 11.12, 11.41, 11.98, 12.22, 15.27, 16.97, 14.14, 18.24,
   

In [282]:
L = 12
T = 36
N = 5

def construct_page_matrix(y, L):
    T = y.shape[0]
    P = np.zeros((L, int(T/L)))

    for j in range(P.shape[1]):
        P[:, j] = y[j*L:(j+1)*L]
    
    return P

def construct_stacked_page_matrix(Y, L):
    N, T = Y.shape
    stacked_P = np.hstack([construct_page_matrix(Y[i, :], L) for i in range (N)])

    return stacked_P

In [283]:
stacked_P = construct_stacked_page_matrix(Y, L)

stacked_P[2, :].sum()

210.65

In [284]:
stacked_P[:5, 0]

array([0., 0., 0., 0., 0.])

In [285]:
stacked_P.shape

(12, 15)

In [286]:
U, S, VT = np.linalg.svd(stacked_P)
print("U.shape =", U.shape)
print("S.shape =", S.shape)
print("VT.shape =", VT.shape)

U.shape = (12, 12)
S.shape = (12,)
VT.shape = (15, 15)


In [287]:
VT.shape

(15, 15)

In [288]:
S.cumsum() / S.sum()

array([0.8264, 0.9009, 0.9181, 0.9347, 0.9499, 0.961 , 0.9709, 0.9802,
       0.9887, 0.9938, 0.9982, 1.    ])

In [289]:
r = 2
S_r = np.diag(S)
S_r = np.hstack([S_r, np.zeros((S_r.shape[0], 3))])
S_r[r:, r:] = 0
S_r.shape

(12, 15)

In [290]:
rho_hat = (N*T - 5) / (N*T)
rho_hat

0.9722222222222222

In [291]:
VT.shape

(15, 15)

In [292]:
np.set_printoptions(precision=4, suppress=True)

P_hat = (1/rho_hat * U @ S_r @ VT)
P_hat[:5, 0]

array([-1.6773, -0.2737,  0.6666,  1.0894,  1.8218])

In [293]:
U, S, VT = np.linalg.svd(Y)
S

array([274.007 ,   7.3519,   6.4945,   5.5289,   4.7904])

In [294]:
S.cumsum() / S.sum()

array([0.919 , 0.9436, 0.9654, 0.9839, 1.    ])

In [295]:
print("U.shape =", U.shape)
print("S.shape =", np.diag(S).shape)
print("VT.shape =", VT.shape)

U.shape = (5, 5)
S.shape = (5, 5)
VT.shape = (36, 36)


In [296]:
r = 1
S_r = np.diag(S)
S_r[r:, r:] = 0
S_r = np.hstack([S_r, np.zeros((S_r.shape[0], VT.shape[0]-S_r.shape[1]))])
S_r.shape

(5, 36)

In [297]:
1/rho_hat * (U @ S_r @ VT)

array([[-0.1432,  1.0752,  1.7716,  2.377 ,  3.3773,  4.5657,  6.3416,
         6.6921,  8.3557,  9.033 , 10.8401, 11.3303, 12.1514, 13.0901,
        14.6276, 15.1861, 15.517 , 17.289 , 18.8658, 19.5731, 20.037 ,
        21.7491, 22.8258, 23.57  , 24.5207, 25.2329, 26.3789, 27.3617,
        29.0035, 29.4971, 30.8023, 31.7863, 32.8087, 33.0018, 34.5558,
        35.3239],
       [-0.146 ,  1.0964,  1.8066,  2.424 ,  3.444 ,  4.6559,  6.4668,
         6.8242,  8.5207,  9.2114, 11.0541, 11.5541, 12.3913, 13.3486,
        14.9164, 15.4859, 15.8234, 17.6304, 19.2383, 19.9596, 20.4327,
        22.1785, 23.2765, 24.0354, 25.0048, 25.7311, 26.8997, 27.902 ,
        29.5762, 30.0795, 31.4105, 32.414 , 33.4565, 33.6534, 35.2382,
        36.0214],
       [-0.1451,  1.0894,  1.795 ,  2.4085,  3.4219,  4.6261,  6.4255,
         6.7806,  8.4662,  9.1525, 10.9834, 11.4802, 12.3121, 13.2632,
        14.821 , 15.3869, 15.7222, 17.5176, 19.1153, 19.832 , 20.302 ,
        22.0367, 23.1277, 23.8816, 24.844