In [130]:
import numpy as np

In [131]:
results = "HTTTHHTTT"
pos = 0

for result in results:
    if result == "H":
        pos += 1
    else:
        pos -= 1

pos

-3

In [132]:
p = 3/4
t = 20
E_Xt = t*(2*p - 1)
E_Xt2 = t + t*(t-1)*(2*p-1)**2

var = E_Xt2 - E_Xt**2
var

15.0

In [133]:
2*p - 1

0.5

In [134]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [135]:
data = [0.4615389710760352, 1.769400733974482, 0.19581427277443453, 2.5240960936236094, 0.896111358581972, 0.6290864932121957, 0.9141040782383563, -0.5882766599718554, -1.5917510609356, -1.873706875223704, -2.431499341231343, -1.9152350528630826, 0.24653667829850678, 1.618510502004899, -0.23205544549864254, 1.8405816444017307, 3.74003005186653, 4.21793075839798, 4.327873685241645, 4.915347380117408, 4.720332088936803, 5.335274145783192, 6.4000586516451525, 6.932585922333053, 7.1007491353596635, 7.756868615874001, 8.319213233877978, 8.816183422797733, 8.336994855455323, 7.268770124891023, 8.914191499726073, 8.154902931055453, 7.361728977521851, 7.013864281520718, 6.844026249030305, 7.389350503413163, 8.429825008740107, 7.008293952513643, 7.7469455865647605, 9.23733098427278]

s = pd.Series(data)
s.index = range(1, len(s)+1)
T = len(s)
s.head()


1    0.461539
2    1.769401
3    0.195814
4    2.524096
5    0.896111
dtype: float64

In [136]:
s.sum()

168.75192843739833

In [137]:
s_0 = pd.concat([pd.Series(0), s])[:-1]
s_0.tail()

35    6.844026
36    7.389351
37    8.429825
38    7.008294
39    7.746946
dtype: float64

In [138]:
Phi = s_0.to_numpy()[:, np.newaxis]
Phi.T @ Phi

array([[1159.17405547]])

In [139]:
1 / (Phi.T @ Phi) @ Phi.T @ s.to_numpy()

array([1.01546676])

In [140]:
alpha_hat_1 = 1 / (Phi.T @ Phi) @ Phi.T @ s.to_numpy()
alpha_hat_1

array([1.01546676])

In [151]:
from statsmodels.tsa.stattools import adfuller
# Perform the ADF test
result = adfuller(s)

# Output the results
print('ADF Statistic:', result[0])
print('p-value:', result[1])
print('Number of lags used:', result[2])
print('Number of observations used:', result[3])
print('Critical Values:', result[4])

ADF Statistic: -0.5647129671622801
p-value: 0.8787577825263682
Number of lags used: 2
Number of observations used: 37
Critical Values: {'1%': -3.6209175221605827, '5%': -2.9435394610388332, '10%': -2.6104002410518627}
