In [25]:
import numpy as np

In [26]:
P = np.array([0.4, 0.6])  # probability measure
S0 = 10  # stock price at t=0
S1 = np.array([20, 5])  # possible stock prices at t=1
np.dot(P, S1)  # expected value of S1

11.0

In [27]:
R = S1 - S0  # possible returns at S1
E_R = np.dot(P, R)  # Expected return
E_r = E_R / S0  # Expected rate of return

print("Expected return:", E_R)
print("Expected rate of return:", E_r)

Expected return: 1.0
Expected rate of return: 0.1


In [28]:
# Variance of returns
sigma2 = np.dot(P, (R/S0 - E_r)**2)
sigma = np.sqrt(sigma2)

print("variance:", sigma2)
print("std:", sigma)

variance: 0.54
std: 0.7348469228349535


In [29]:
B = [10, np.array([11, 11])]
S = [10, np.array([20, 5])]
M = np.array([B[1], S[1]]).T  # t=1 prices matrix
M

array([[11, 20],
       [11,  5]])

In [30]:
K = 15
C1 = np.maximum(S[1]-K, 0)  # payoffs of call option with K=15
C1

array([5, 0])

In [32]:
phi = np.linalg.solve(M, C1)  # M @ phi = C1, solution to this equation.
phi

array([-0.15151515,  0.33333333])

In [33]:
# Price of the call option by replication
C0 = np.dot(phi, np.array([B[0], S[0]]))
print("C0 =", C0)

C0 = 1.8181818181818183
