In [45]:
import numpy as np

In [46]:
def update_a(a):
    return a / (a+2) + 1
def update_b(b):
    return 0.2 + b/2
a = 0
b = 0

for i in range(100):
    a = update_a(a)
    b = update_b(b)
    
print("a =", np.round(a, 4))
print("b =", b)


a = 1.4142
b = 0.4


In [47]:
def update_a(a):
    return (a/2 + 1)

def update_b(a, b):
    return a/2 + b/2

a = 0
b = 0
for i in range(1000):
    a = update_a(a)
    b = update_b(a, b)
    
print("a =", np.round(a, 4))
print("b =", b)

a = 2.0
b = 2.0


In [48]:
# FITTED VALUE ITERATION

def f(s, a):  # transition function
    demand = np.random.normal(0.5, 0.3, 1)
    return np.maximum(np.minimum(s + a - demand, 10), 0)
def g(s, a):  # reward function
    return 2*s - a

S = np.linspace(0.5, 9.5, 10)  # state space
C = np.zeros(3)  # coefficients vector, initializie at 0
A = np.array([0, 1, 2])  # Action space, quantity of items to reorder
gamma = 0.7  # discount factor
eta = 1e-5  # learning rate

In [49]:
86000/6 / 3600

3.981481481481482

In [50]:
np.set_printoptions(precision=4, suppress=True)

def approximate_E_V_tilde(s, A, C, n=100):
    demand = np.random.normal(0.5, 0.3, (3, n))
    s_values = np.maximum(np.minimum(s + A[:, np.newaxis] - demand, 10), 0)[:, :, np.newaxis]
    s_poly = np.concatenate([np.ones(s_values.shape), s_values, s_values**2], axis=2)
    
    E_V_tilde = (s_poly @ C).mean(axis=1)
    return E_V_tilde

def calc_V_hats(S, A, C, gamma, n=100):
    V_hat_arr = []
    a_hat_arr = []
    for s in S:
        E_V_tilde = approximate_E_V_tilde(s, A, C, n)
        V_hat = np.max(g(s, A) + gamma*E_V_tilde)
        a_hat = np.argmax(g(s, A) + gamma*E_V_tilde)  # optimum action
        
        V_hat_arr.append(V_hat)
        a_hat_arr.append(a_hat)
    
    V_hat_arr = np.array(V_hat_arr)
    a_hat_arr = np.array(a_hat_arr)
        
    return V_hat_arr, a_hat_arr

def fitted_value_iteration(S, A, C, gamma, n=100, epsilon=1e-6):
    S_poly = np.concatenate([np.ones(len(S))[:, np.newaxis], S[:, np.newaxis], (S**2)[:, np.newaxis]], axis=1)  # (10, 3)
    
    M = len(S)
    C_old = np.inf
    num_iter = 0
    while np.abs(C - C_old).max() > epsilon:
        num_iter += 1
        C_old = C
        print("C_old =", C_old)
        
        V_tilde_arr = S_poly @ C
        a_hat_arr, V_hat_arr = calc_V_hats(S, A, C, gamma, n)
        
        C = C - eta*2*(S_poly * (V_tilde_arr - V_hat_arr)[:, np.newaxis])  # gradient descent
        print("C_new =", C)
    print("Iteration count:", num_iter)
    return a_hat_arr, V_hat_arr, C
        
        

S = np.linspace(0.5, 9.5, 10)  # state space
C = np.zeros(3)  # coefficients vector, initializie at 0
A = np.array([0, 1, 2])  # Action space, quantity of items to reorder
gamma = 0.7  # discount factor
eta = 1e-5  # learning rate
n = 100

a_hat_arr, V_hat_arr, C = fitted_value_iteration(S, A, C, gamma, n=100, epsilon=1e-6)


C_old = [0. 0. 0.]
C_new = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Iteration count: 1
